### ISSUE TITLE
Diagrama de componentes

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo-v-a-k#1]
[Reporte DiagramaComponentes.pdf](https://github.com/user-attachments/files/18002987/Reporte.DiagramaComponentes.pdf)
  Wiki: 
https://github.com/SistemasTecTlaxiaco/Loc-Serv/wiki/11-Arquitectura-de-Software-para-Web-3.0#5-diagrama-de-componentes

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rubrica tiene 28 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
